version: '2'
services:
  zookeeper-1a:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper-1a
    container_name: zookeeper-1a
    ports:
      - "12181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  broker-1a:
    image: confluentinc/cp-kafka:5.3.1
    hostname: broker-1a
    container_name: broker-1a
    depends_on:
      - zookeeper-1a
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 'r1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1a:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${PUBLIC_IP}:19092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9994
    restart: always

  schema-registry-4:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry-4
    container_name: schema-registry-4   
    ports:
      - "28033:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-4
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: 'true'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: 'full'
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper-1:2181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: '192.168.73.86:9092,192.168.73.86:9093'
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: "false"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'
    restart: always

  kafka-setup:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on:
      - broker-1a
      - zookeeper-1a
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b broker-1a:9092 1 120 && \
                       kafka-topics --create --if-not-exists --zookeeper zookeeper-1a:2181 --partitions 8 --replication-factor 3 --topic person-v1 && \
                       kafka-topics --create --if-not-exists --zookeeper zookeeper-1a:2181 --partitions 8 --replication-factor 3 --topic person-v2
                 '"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored 