sudo: true
language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
env:
    - LIBRDKAFKA_VERSION=0.8.6
    - LIBRDKAFKA_VERSION=0.8
    - LIBRDKAFKA_VERSION=0.9.5.x
    - LIBRDKAFKA_VERSION=master
script: ./travis.sh
