spring:
  
  kafka:
    bootstrap-servers: 192.168.25.187:9092
    kafka.acks: all
    retries: 0
    consumer:
      auto-offset-reset: earliest
      group-id: customer-group      
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    schema-registry-url: http://192.168.25.187:8081

  jackson.serialization.indent_output: true
  
kafka:
  topic:
    customer: customer